doctrine:
    dbal:
        driver: 'pdo_sqlite'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        options:
            1002: true  # PDO::SQLITE_ATTR_ENABLE_FKEYS = 1002 (enables foreign keys)     
        use_savepoints: true
                 

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            

            AssetDiscovery:
                is_bundle: false
                type: attribute 
                dir: '%kernel.project_dir%/src/Modules/AssetDiscovery/Entity'
                prefix: 'App\Modules\AssetDiscovery\Entity'
                alias: AssetDiscovery

            AssetVulnerability:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/AssetVulnerability/Entity'
                prefix: 'App\Modules\AssetVulnerability\Entity'
                alias: AssetVulnerability

            ScanManagement:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Modules/ScanManagement/Entity'
                prefix: 'App\Modules\ScanManagement\Entity'
                alias: ScanManagement




when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
