controllers:
    resource: ../src/Controller/
    type: attribute
dashboard:
    path: /dashboard
    controller: App\Modules\Dashboard\Controller\DashboardController::index
user_registration:
    path: /register
    controller: App\Modules\UserManagement\Controller\RegistrationController::register
admin_user_list:
    path: /admin/users
    controller: App\Modules\UserManagement\Controller\AdminUserController::list

admin_user_edit:
    path: /admin/users/{id}/edit
    controller: App\Modules\UserManagement\Controller\AdminUserController::edit
    requirements:
        id: \d+
admin_user_create:
  path: /admin/users/create
  controller: App\Modules\UserManagement\Controller\AdminUserController::create

admin_user_delete:
  path: /admin/users/{id}/delete
  controller: App\Modules\UserManagement\Controller\AdminUserController::delete
  methods: [POST]

asset_list:
    path: /assets/
    controller: App\Modules\AssetDiscovery\Controller\AssetController::list

asset_create:
    path: /assets/create
    controller: App\Modules\AssetDiscovery\Controller\AssetController::create

asset_edit:
    path: /assets/{id}/edit
    controller: App\Modules\AssetDiscovery\Controller\AssetController::edit
    requirements:
        id: \d+

asset_delete:
    path: /assets/{id}/delete
    controller: App\Modules\AssetDiscovery\Controller\AssetController::delete
    methods: [POST]

asset_detail:
    path: /assets/{id}
    controller: App\Modules\AssetDiscovery\Controller\AssetController::detail
    methods: GET


    # config/routes.yaml

# Other route imports...

asset_vulnerability:
    resource: '../src/Modules/AssetVulnerability/Controller/'
    type: annotation
    prefix: /vulnerabilities

